[2025-03-31T06:58:43.443+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T06:58:43.627+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_weather_etl.run_minio_script manual__2025-03-31T06:58:28.607466+00:00 [queued]>
[2025-03-31T06:58:43.647+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_weather_etl.run_minio_script manual__2025-03-31T06:58:28.607466+00:00 [queued]>
[2025-03-31T06:58:43.651+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-31T06:58:43.674+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_minio_script> on 2025-03-31 06:58:28.607466+00:00
[2025-03-31T06:58:43.682+0000] {standard_task_runner.py:72} INFO - Started process 4502 to run task
[2025-03-31T06:58:43.688+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'daily_weather_etl', 'run_minio_script', 'manual__2025-03-31T06:58:28.607466+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp0nrrf67p']
[2025-03-31T06:58:43.691+0000] {standard_task_runner.py:105} INFO - Job 186: Subtask run_minio_script
[2025-03-31T06:58:43.765+0000] {task_command.py:467} INFO - Running <TaskInstance: daily_weather_etl.run_minio_script manual__2025-03-31T06:58:28.607466+00:00 [running]> on host 3c3c1f66214b
[2025-03-31T06:58:43.893+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_weather_etl' AIRFLOW_CTX_TASK_ID='run_minio_script' AIRFLOW_CTX_EXECUTION_DATE='2025-03-31T06:58:28.607466+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-31T06:58:28.607466+00:00'
[2025-03-31T06:58:43.897+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-31T06:58:43.899+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-31T06:58:43.902+0000] {logging_mixin.py:190} INFO - Current task name:run_minio_script state:running start_date:2025-03-31 06:58:43.629481+00:00
[2025-03-31T06:58:43.904+0000] {logging_mixin.py:190} INFO - Dag name:daily_weather_etl and current dag run status:running
[2025-03-31T06:58:43.906+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-31T06:58:43.908+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-31T06:58:43.910+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/minio.py']
[2025-03-31T06:58:43.926+0000] {subprocess.py:99} INFO - Output:
[2025-03-31T06:58:48.163+0000] {subprocess.py:106} INFO - Setting default log level to "WARN".
[2025-03-31T06:58:48.165+0000] {subprocess.py:106} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-03-31T06:58:48.515+0000] {subprocess.py:106} INFO - 25/03/31 06:58:48 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-31T06:59:01.670+0000] {subprocess.py:106} INFO - [Stage 0:>                                                          (0 + 8) / 8]25/03/31 06:59:01 ERROR Executor: Exception in task 6.0 in stage 0.0 (TID 6)
[2025-03-31T06:59:01.672+0000] {subprocess.py:106} INFO - org.apache.spark.api.python.PythonException: Traceback (most recent call last):
[2025-03-31T06:59:01.682+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/utils.py", line 179, in map_to_description
[2025-03-31T06:59:01.687+0000] {subprocess.py:106} INFO -     return icon_mapping[weathercode]['description']
[2025-03-31T06:59:01.697+0000] {subprocess.py:106} INFO - KeyError: None
[2025-03-31T06:59:01.699+0000] {subprocess.py:106} INFO - 
[2025-03-31T06:59:01.701+0000] {subprocess.py:106} INFO - 	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:572)
[2025-03-31T06:59:01.702+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.python.BasePythonUDFRunner$$anon$1.read(PythonUDFRunner.scala:94)
[2025-03-31T06:59:01.704+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.python.BasePythonUDFRunner$$anon$1.read(PythonUDFRunner.scala:75)
[2025-03-31T06:59:01.713+0000] {subprocess.py:106} INFO - 	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:525)
[2025-03-31T06:59:01.715+0000] {subprocess.py:106} INFO - 	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
[2025-03-31T06:59:01.717+0000] {subprocess.py:106} INFO - 	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
[2025-03-31T06:59:01.720+0000] {subprocess.py:106} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-03-31T06:59:01.734+0000] {subprocess.py:106} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-03-31T06:59:01.749+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
[2025-03-31T06:59:01.753+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-03-31T06:59:01.774+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
[2025-03-31T06:59:01.784+0000] {subprocess.py:106} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-03-31T06:59:01.786+0000] {subprocess.py:106} INFO - 	at scala.collection.Iterator.isEmpty(Iterator.scala:387)
[2025-03-31T06:59:01.788+0000] {subprocess.py:106} INFO - 	at scala.collection.Iterator.isEmpty$(Iterator.scala:387)
[2025-03-31T06:59:01.794+0000] {subprocess.py:106} INFO - 	at scala.collection.AbstractIterator.isEmpty(Iterator.scala:1431)
[2025-03-31T06:59:01.802+0000] {subprocess.py:106} INFO - 	at scala.collection.TraversableOnce.nonEmpty(TraversableOnce.scala:143)
[2025-03-31T06:59:01.804+0000] {subprocess.py:106} INFO - 	at scala.collection.TraversableOnce.nonEmpty$(TraversableOnce.scala:143)
[2025-03-31T06:59:01.805+0000] {subprocess.py:106} INFO - 	at scala.collection.AbstractIterator.nonEmpty(Iterator.scala:1431)
[2025-03-31T06:59:01.807+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$takeOrdered$2(RDD.scala:1559)
[2025-03-31T06:59:01.809+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$takeOrdered$2$adapted(RDD.scala:1558)
[2025-03-31T06:59:01.815+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndex$2(RDD.scala:910)
[2025-03-31T06:59:01.818+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndex$2$adapted(RDD.scala:910)
[2025-03-31T06:59:01.823+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-03-31T06:59:01.829+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-03-31T06:59:01.834+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-03-31T06:59:01.836+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-31T06:59:01.838+0000] {subprocess.py:106} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-31T06:59:01.840+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-31T06:59:01.842+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-31T06:59:01.848+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-31T06:59:01.851+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-31T06:59:01.853+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-31T06:59:01.854+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-31T06:59:01.858+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-03-31T06:59:01.864+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-03-31T06:59:01.867+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-31T06:59:01.869+0000] {subprocess.py:106} INFO - 25/03/31 06:59:01 ERROR Executor: Exception in task 7.0 in stage 0.0 (TID 7)
[2025-03-31T06:59:01.872+0000] {subprocess.py:106} INFO - org.apache.spark.api.python.PythonException: Traceback (most recent call last):
[2025-03-31T06:59:01.876+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/utils.py", line 179, in map_to_description
[2025-03-31T06:59:01.879+0000] {subprocess.py:106} INFO -     return icon_mapping[weathercode]['description']
[2025-03-31T06:59:01.881+0000] {subprocess.py:106} INFO - KeyError: None
[2025-03-31T06:59:01.883+0000] {subprocess.py:106} INFO - 
[2025-03-31T06:59:01.884+0000] {subprocess.py:106} INFO - 	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:572)
[2025-03-31T06:59:01.886+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.python.BasePythonUDFRunner$$anon$1.read(PythonUDFRunner.scala:94)
[2025-03-31T06:59:01.887+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.python.BasePythonUDFRunner$$anon$1.read(PythonUDFRunner.scala:75)
[2025-03-31T06:59:01.896+0000] {subprocess.py:106} INFO - 	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:525)
[2025-03-31T06:59:01.898+0000] {subprocess.py:106} INFO - 	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
[2025-03-31T06:59:01.900+0000] {subprocess.py:106} INFO - 	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
[2025-03-31T06:59:01.901+0000] {subprocess.py:106} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-03-31T06:59:01.903+0000] {subprocess.py:106} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-03-31T06:59:01.905+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
[2025-03-31T06:59:01.908+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-03-31T06:59:01.917+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
[2025-03-31T06:59:01.918+0000] {subprocess.py:106} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-03-31T06:59:01.920+0000] {subprocess.py:106} INFO - 	at scala.collection.Iterator.isEmpty(Iterator.scala:387)
[2025-03-31T06:59:01.922+0000] {subprocess.py:106} INFO - 	at scala.collection.Iterator.isEmpty$(Iterator.scala:387)
[2025-03-31T06:59:01.924+0000] {subprocess.py:106} INFO - 	at scala.collection.AbstractIterator.isEmpty(Iterator.scala:1431)
[2025-03-31T06:59:01.927+0000] {subprocess.py:106} INFO - 	at scala.collection.TraversableOnce.nonEmpty(TraversableOnce.scala:143)
[2025-03-31T06:59:01.930+0000] {subprocess.py:106} INFO - 	at scala.collection.TraversableOnce.nonEmpty$(TraversableOnce.scala:143)
[2025-03-31T06:59:01.933+0000] {subprocess.py:106} INFO - 	at scala.collection.AbstractIterator.nonEmpty(Iterator.scala:1431)
[2025-03-31T06:59:01.938+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$takeOrdered$2(RDD.scala:1559)
[2025-03-31T06:59:01.943+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$takeOrdered$2$adapted(RDD.scala:1558)
[2025-03-31T06:59:01.951+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndex$2(RDD.scala:910)
[2025-03-31T06:59:01.952+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndex$2$adapted(RDD.scala:910)
[2025-03-31T06:59:01.954+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-03-31T06:59:01.956+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-03-31T06:59:01.957+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-03-31T06:59:01.959+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-31T06:59:01.962+0000] {subprocess.py:106} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-31T06:59:01.965+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-31T06:59:01.966+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-31T06:59:01.968+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-31T06:59:01.970+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-31T06:59:01.972+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-31T06:59:01.973+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-31T06:59:01.975+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-03-31T06:59:01.977+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-03-31T06:59:01.980+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-31T06:59:01.982+0000] {subprocess.py:106} INFO - 25/03/31 06:59:01 WARN TaskSetManager: Lost task 6.0 in stage 0.0 (TID 6) (3c3c1f66214b executor driver): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
[2025-03-31T06:59:01.984+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/utils.py", line 179, in map_to_description
[2025-03-31T06:59:01.986+0000] {subprocess.py:106} INFO -     return icon_mapping[weathercode]['description']
[2025-03-31T06:59:01.987+0000] {subprocess.py:106} INFO - KeyError: None
[2025-03-31T06:59:01.989+0000] {subprocess.py:106} INFO - 
[2025-03-31T06:59:01.991+0000] {subprocess.py:106} INFO - 	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:572)
[2025-03-31T06:59:01.993+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.python.BasePythonUDFRunner$$anon$1.read(PythonUDFRunner.scala:94)
[2025-03-31T06:59:01.996+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.python.BasePythonUDFRunner$$anon$1.read(PythonUDFRunner.scala:75)
[2025-03-31T06:59:01.998+0000] {subprocess.py:106} INFO - 	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:525)
[2025-03-31T06:59:02.000+0000] {subprocess.py:106} INFO - 	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
[2025-03-31T06:59:02.003+0000] {subprocess.py:106} INFO - 	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
[2025-03-31T06:59:02.004+0000] {subprocess.py:106} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-03-31T06:59:02.005+0000] {subprocess.py:106} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-03-31T06:59:02.007+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
[2025-03-31T06:59:02.010+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-03-31T06:59:02.013+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
[2025-03-31T06:59:02.015+0000] {subprocess.py:106} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-03-31T06:59:02.017+0000] {subprocess.py:106} INFO - 	at scala.collection.Iterator.isEmpty(Iterator.scala:387)
[2025-03-31T06:59:02.018+0000] {subprocess.py:106} INFO - 	at scala.collection.Iterator.isEmpty$(Iterator.scala:387)
[2025-03-31T06:59:02.020+0000] {subprocess.py:106} INFO - 	at scala.collection.AbstractIterator.isEmpty(Iterator.scala:1431)
[2025-03-31T06:59:02.021+0000] {subprocess.py:106} INFO - 	at scala.collection.TraversableOnce.nonEmpty(TraversableOnce.scala:143)
[2025-03-31T06:59:02.023+0000] {subprocess.py:106} INFO - 	at scala.collection.TraversableOnce.nonEmpty$(TraversableOnce.scala:143)
[2025-03-31T06:59:02.026+0000] {subprocess.py:106} INFO - 	at scala.collection.AbstractIterator.nonEmpty(Iterator.scala:1431)
[2025-03-31T06:59:02.029+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$takeOrdered$2(RDD.scala:1559)
[2025-03-31T06:59:02.031+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$takeOrdered$2$adapted(RDD.scala:1558)
[2025-03-31T06:59:02.032+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndex$2(RDD.scala:910)
[2025-03-31T06:59:02.034+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndex$2$adapted(RDD.scala:910)
[2025-03-31T06:59:02.036+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-03-31T06:59:02.037+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-03-31T06:59:02.038+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-03-31T06:59:02.040+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-31T06:59:02.042+0000] {subprocess.py:106} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-31T06:59:02.046+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-31T06:59:02.047+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-31T06:59:02.049+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-31T06:59:02.050+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-31T06:59:02.052+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-31T06:59:02.054+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-31T06:59:02.055+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-03-31T06:59:02.057+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-03-31T06:59:02.062+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-31T06:59:02.064+0000] {subprocess.py:106} INFO - 
[2025-03-31T06:59:02.065+0000] {subprocess.py:106} INFO - 25/03/31 06:59:01 ERROR TaskSetManager: Task 6 in stage 0.0 failed 1 times; aborting job
[2025-03-31T06:59:02.821+0000] {subprocess.py:106} INFO - [Stage 0:=======>                                                   (1 + 7) / 8]Error:
[2025-03-31T06:59:02.827+0000] {subprocess.py:106} INFO -   An exception was thrown from the Python worker. Please see the stack trace below.
[2025-03-31T06:59:02.833+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-03-31T06:59:02.837+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/utils.py", line 179, in map_to_description
[2025-03-31T06:59:02.841+0000] {subprocess.py:106} INFO -     return icon_mapping[weathercode]['description']
[2025-03-31T06:59:02.846+0000] {subprocess.py:106} INFO - KeyError: None
[2025-03-31T06:59:02.849+0000] {subprocess.py:106} INFO - 
[2025-03-31T06:59:03.486+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-31T06:59:03.522+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-31T06:59:03.525+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=daily_weather_etl, task_id=run_minio_script, run_id=manual__2025-03-31T06:58:28.607466+00:00, execution_date=20250331T065828, start_date=20250331T065843, end_date=20250331T065903
[2025-03-31T06:59:03.563+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-31T06:59:03.565+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-31T06:59:03.567+0000] {logging_mixin.py:190} INFO - Dag name:daily_weather_etl queued_at:2025-03-31 06:58:28.651669+00:00
[2025-03-31T06:59:03.569+0000] {logging_mixin.py:190} INFO - Task hostname:3c3c1f66214b operator:BashOperator
[2025-03-31T06:59:03.591+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-31T06:59:03.615+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-31T06:59:03.619+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
