[2025-04-07T06:35:29.977+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-07T06:35:30.009+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_weather_etl.run_minio_script scheduled__2025-04-04T07:00:00+00:00 [queued]>
[2025-04-07T06:35:30.026+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_weather_etl.run_minio_script scheduled__2025-04-04T07:00:00+00:00 [queued]>
[2025-04-07T06:35:30.045+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-07T06:35:30.070+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_minio_script> on 2025-04-04 07:00:00+00:00
[2025-04-07T06:35:30.078+0000] {standard_task_runner.py:72} INFO - Started process 389 to run task
[2025-04-07T06:35:30.084+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'daily_weather_etl', 'run_minio_script', 'scheduled__2025-04-04T07:00:00+00:00', '--job-id', '228', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpjyfd7bw3']
[2025-04-07T06:35:30.087+0000] {standard_task_runner.py:105} INFO - Job 228: Subtask run_minio_script
[2025-04-07T06:35:30.161+0000] {task_command.py:467} INFO - Running <TaskInstance: daily_weather_etl.run_minio_script scheduled__2025-04-04T07:00:00+00:00 [running]> on host 3c3c1f66214b
[2025-04-07T06:35:30.525+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_weather_etl' AIRFLOW_CTX_TASK_ID='run_minio_script' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T07:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-04T07:00:00+00:00'
[2025-04-07T06:35:30.527+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-07T06:35:30.528+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-07T06:35:30.529+0000] {logging_mixin.py:190} INFO - Current task name:run_minio_script state:running start_date:2025-04-07 06:35:30.010943+00:00
[2025-04-07T06:35:30.530+0000] {logging_mixin.py:190} INFO - Dag name:daily_weather_etl and current dag run status:running
[2025-04-07T06:35:30.532+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-07T06:35:30.533+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-07T06:35:30.535+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/minio.py']
[2025-04-07T06:35:30.553+0000] {subprocess.py:99} INFO - Output:
[2025-04-07T06:35:35.084+0000] {subprocess.py:106} INFO - Setting default log level to "WARN".
[2025-04-07T06:35:35.085+0000] {subprocess.py:106} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-04-07T06:35:35.664+0000] {subprocess.py:106} INFO - 25/04/07 06:35:35 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-04-07T06:35:37.503+0000] {subprocess.py:106} INFO - 25/04/07 06:35:37 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2025-04-07T06:36:09.332+0000] {subprocess.py:106} INFO - [Stage 0:>                                                          (0 + 8) / 8]                                                                                [Stage 1:=======>                                                   (1 + 7) / 8][Stage 1:===================================================>       (7 + 1) / 8]                                                                                [Stage 2:==============>                                            (2 + 6) / 8]                                                                                [Stage 10:===========================================>              (6 + 2) / 8][Stage 11:==================================================>       (7 + 1) / 8]                                                                                [Stage 12:==================================================>       (7 + 1) / 8][Stage 13:==================================================>       (7 + 1) / 8]                                                                                +-----+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-04-07T06:36:09.334+0000] {subprocess.py:106} INFO - |city |date      |time |temperature|wind_kph|humidity|feelslike|precip_mm|text         |icon                                          |
[2025-04-07T06:36:09.336+0000] {subprocess.py:106} INFO - +-----+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-04-07T06:36:09.339+0000] {subprocess.py:106} INFO - |elche|2025-04-05|09:00|15.4       |11.7    |61      |15.4     |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-04-07T06:36:09.341+0000] {subprocess.py:106} INFO - |elche|2025-04-05|04:00|16.1       |15.7    |58      |16.1     |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-04-07T06:36:09.344+0000] {subprocess.py:106} INFO - |elche|2025-04-05|15:00|24.5       |16.0    |22      |24.5     |0.0      |Partly Cloudy|//cdn.weatherapi.com/weather/64x64/day/116.png|
[2025-04-07T06:36:09.346+0000] {subprocess.py:106} INFO - |elche|2025-04-05|22:00|17.6       |5.1     |59      |17.6     |0.0      |Cloudy       |//cdn.weatherapi.com/weather/64x64/day/119.png|
[2025-04-07T06:36:09.353+0000] {subprocess.py:106} INFO - +-----+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-04-07T06:36:09.361+0000] {subprocess.py:106} INFO - 
[2025-04-07T06:36:09.363+0000] {subprocess.py:106} INFO - +------+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-04-07T06:36:09.365+0000] {subprocess.py:106} INFO - |city  |date      |time |temperature|wind_kph|humidity|feelslike|precip_mm|text         |icon                                          |
[2025-04-07T06:36:09.367+0000] {subprocess.py:106} INFO - +------+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-04-07T06:36:09.369+0000] {subprocess.py:106} INFO - |madrid|2025-04-05|09:00|8.8        |9.7     |91      |8.8      |0.0      |Partly Cloudy|//cdn.weatherapi.com/weather/64x64/day/116.png|
[2025-04-07T06:36:09.371+0000] {subprocess.py:106} INFO - |madrid|2025-04-05|15:00|14.3       |7.8     |58      |14.3     |0.1      |Light Drizzle|//cdn.weatherapi.com/weather/64x64/day/176.png|
[2025-04-07T06:36:09.373+0000] {subprocess.py:106} INFO - |madrid|2025-04-05|22:00|11.2       |6.6     |74      |11.2     |0.0      |Cloudy       |//cdn.weatherapi.com/weather/64x64/day/119.png|
[2025-04-07T06:36:09.376+0000] {subprocess.py:106} INFO - |madrid|2025-04-05|04:00|9.2        |12.5    |93      |9.2      |0.0      |Cloudy       |//cdn.weatherapi.com/weather/64x64/day/119.png|
[2025-04-07T06:36:09.378+0000] {subprocess.py:106} INFO - +------+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-04-07T06:36:09.381+0000] {subprocess.py:106} INFO - 
[2025-04-07T06:36:09.383+0000] {subprocess.py:106} INFO - +--------------------+----------+-----+-----------+--------+--------+---------+---------+------------+----------------------------------------------+
[2025-04-07T06:36:09.385+0000] {subprocess.py:106} INFO - |city                |date      |time |temperature|wind_kph|humidity|feelslike|precip_mm|text        |icon                                          |
[2025-04-07T06:36:09.387+0000] {subprocess.py:106} INFO - +--------------------+----------+-----+-----------+--------+--------+---------+---------+------------+----------------------------------------------+
[2025-04-07T06:36:09.389+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-05|04:00|13.6       |4.9     |81      |13.6     |0.0      |Sunny       |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-04-07T06:36:09.391+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-05|22:00|16.5       |3.4     |68      |16.5     |0.0      |Mostly Clear|//cdn.weatherapi.com/weather/64x64/day/116.png|
[2025-04-07T06:36:09.393+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-05|09:00|15.6       |7.9     |60      |15.6     |0.0      |Sunny       |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-04-07T06:36:09.395+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-05|15:00|23.9       |16.5    |24      |23.9     |0.0      |Sunny       |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-04-07T06:36:09.397+0000] {subprocess.py:106} INFO - +--------------------+----------+-----+-----------+--------+--------+---------+---------+------------+----------------------------------------------+
[2025-04-07T06:36:09.399+0000] {subprocess.py:106} INFO - 
[2025-04-07T06:36:09.400+0000] {subprocess.py:106} INFO - +----------+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-04-07T06:36:09.402+0000] {subprocess.py:106} INFO - |city      |date      |time |temperature|wind_kph|humidity|feelslike|precip_mm|text         |icon                                          |
[2025-04-07T06:36:09.404+0000] {subprocess.py:106} INFO - +----------+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-04-07T06:36:09.405+0000] {subprocess.py:106} INFO - |torrevieja|2025-04-05|04:00|14.0       |4.9     |98      |14.0     |0.0      |Partly Cloudy|//cdn.weatherapi.com/weather/64x64/day/116.png|
[2025-04-07T06:36:09.407+0000] {subprocess.py:106} INFO - |torrevieja|2025-04-05|09:00|15.3       |12.1    |72      |15.3     |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-04-07T06:36:09.409+0000] {subprocess.py:106} INFO - |torrevieja|2025-04-05|15:00|22.8       |12.2    |36      |22.8     |0.0      |Cloudy       |//cdn.weatherapi.com/weather/64x64/day/119.png|
[2025-04-07T06:36:09.411+0000] {subprocess.py:106} INFO - |torrevieja|2025-04-05|22:00|15.7       |5.8     |72      |15.7     |0.0      |Cloudy       |//cdn.weatherapi.com/weather/64x64/day/119.png|
[2025-04-07T06:36:09.414+0000] {subprocess.py:106} INFO - +----------+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-04-07T06:36:09.415+0000] {subprocess.py:106} INFO - 
[2025-04-07T06:36:09.417+0000] {subprocess.py:106} INFO - +--------+----------+-----+-----------+--------+--------+---------+---------+------------+----------------------------------------------+
[2025-04-07T06:36:09.419+0000] {subprocess.py:106} INFO - |city    |date      |time |temperature|wind_kph|humidity|feelslike|precip_mm|text        |icon                                          |
[2025-04-07T06:36:09.423+0000] {subprocess.py:106} INFO - +--------+----------+-----+-----------+--------+--------+---------+---------+------------+----------------------------------------------+
[2025-04-07T06:36:09.427+0000] {subprocess.py:106} INFO - |valencia|2025-04-05|15:00|23.3       |12.1    |27      |23.3     |0.0      |Sunny       |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-04-07T06:36:09.429+0000] {subprocess.py:106} INFO - |valencia|2025-04-05|09:00|14.4       |15.8    |66      |14.4     |0.0      |Sunny       |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-04-07T06:36:09.432+0000] {subprocess.py:106} INFO - |valencia|2025-04-05|22:00|17.2       |8.1     |58      |17.2     |0.0      |Mostly Clear|//cdn.weatherapi.com/weather/64x64/day/116.png|
[2025-04-07T06:36:09.434+0000] {subprocess.py:106} INFO - |valencia|2025-04-05|04:00|13.3       |7.3     |87      |13.3     |0.0      |Sunny       |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-04-07T06:36:09.437+0000] {subprocess.py:106} INFO - +--------+----------+-----+-----------+--------+--------+---------+---------+------------+----------------------------------------------+
[2025-04-07T06:36:09.442+0000] {subprocess.py:106} INFO - 
[2025-04-07T06:36:15.730+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to None. Terminating instance.
[2025-04-07T06:36:15.732+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-07T06:36:15.741+0000] {process_utils.py:132} INFO - Sending 15 to group 389. PIDs of all processes in the group: [394, 409, 670, 745, 773, 776, 780, 784, 788, 797, 802, 813, 673, 674, 684, 689, 698, 708, 716, 724, 389]
[2025-04-07T06:36:15.742+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 389
[2025-04-07T06:36:15.745+0000] {taskinstance.py:3094} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-07T06:36:15.757+0000] {taskinstance.py:3095} ERROR - Stacktrace: 
  File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
  File "/home/***/.local/lib/python3.9/site-packages/***/__main__.py", line 62, in main
    args.func(args)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/providers/celery/cli/celery_command.py", line 64, in wrapper
    providers_configuration_loaded(func)(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/providers/celery/cli/celery_command.py", line 237, in worker
    _run_command_with_daemon_option(
  File "/home/***/.local/lib/python3.9/site-packages/***/providers/celery/cli/celery_command.py", line 50, in _run_command_with_daemon_option
    run_command_with_daemon_option(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/daemon_utils.py", line 86, in run_command_with_daemon_option
    callback()
  File "/home/***/.local/lib/python3.9/site-packages/***/providers/celery/cli/celery_command.py", line 230, in run_celery_worker
    celery_app.worker_main(options)
  File "/home/***/.local/lib/python3.9/site-packages/celery/app/base.py", line 391, in worker_main
    self.start(argv=argv)
  File "/home/***/.local/lib/python3.9/site-packages/celery/app/base.py", line 371, in start
    celery.main(args=argv, standalone_mode=False)
  File "/home/***/.local/lib/python3.9/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/home/***/.local/lib/python3.9/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/***/.local/lib/python3.9/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/***/.local/lib/python3.9/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/celery/bin/base.py", line 135, in caller
    return f(ctx, *args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
  File "/home/***/.local/lib/python3.9/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
  File "/home/***/.local/lib/python3.9/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/***/.local/lib/python3.9/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/home/***/.local/lib/python3.9/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
  File "/home/***/.local/lib/python3.9/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
  File "/home/***/.local/lib/python3.9/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/billiard/pool.py", line 1046, in __init__
    self._create_worker_process(i)
  File "/home/***/.local/lib/python3.9/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
  File "/home/***/.local/lib/python3.9/site-packages/billiard/pool.py", line 1158, in _create_worker_process
    w.start()
  File "/home/***/.local/lib/python3.9/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
  File "/home/***/.local/lib/python3.9/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
  File "/home/***/.local/lib/python3.9/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
  File "/home/***/.local/lib/python3.9/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
  File "/home/***/.local/lib/python3.9/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
  File "/home/***/.local/lib/python3.9/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/billiard/pool.py", line 292, in __call__
    sys.exit(self.workloop(pid=pid))
  File "/home/***/.local/lib/python3.9/site-packages/billiard/pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "/home/***/.local/lib/python3.9/site-packages/celery/app/trace.py", line 651, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
  File "/home/***/.local/lib/python3.9/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 139, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
  File "/home/***/.local/lib/python3.9/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 171, in _execute_in_fork
    args.func(args)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/task_command.py", line 254, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/task_command.py", line 322, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
  File "/home/***/.local/lib/python3.9/site-packages/***/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
  File "/home/***/.local/lib/python3.9/site-packages/***/jobs/local_task_job_runner.py", line 171, in _execute
    self.task_runner.start()
  File "/home/***/.local/lib/python3.9/site-packages/***/task/task_runner/standard_task_runner.py", line 55, in start
    self.process = self._start_by_fork()
  File "/home/***/.local/lib/python3.9/site-packages/***/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/***/.local/lib/python3.9/site-packages/***/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/***/.local/lib/python3.9/site-packages/***/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/***/.local/lib/python3.9/site-packages/***/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/***/.local/lib/python3.9/site-packages/***/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/operators/bash.py", line 257, in execute
    result = self._run_inline_command(bash_path=bash_path, env=env)
  File "/home/***/.local/lib/python3.9/site-packages/***/operators/bash.py", line 284, in _run_inline_command
    return self.subprocess_hook.run_command(
  File "/home/***/.local/lib/python3.9/site-packages/***/hooks/subprocess.py", line 104, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/***/.local/lib/python3.9/site-packages/***/models/taskinstance.py", line 3095, in signal_handler
    self.log.error("Stacktrace: \n%s", "".join(traceback.format_stack()))

[2025-04-07T06:36:15.764+0000] {subprocess.py:117} INFO - Sending SIGTERM signal to process group
[2025-04-07T06:36:15.784+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 257, in execute
    result = self._run_inline_command(bash_path=bash_path, env=env)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 284, in _run_inline_command
    return self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/hooks/subprocess.py", line 104, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3097, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-04-07T06:36:15.790+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-07T06:36:15.791+0000] {logging_mixin.py:190} INFO - Task start:2025-04-07 06:35:30.010943+00:00 end:2025-04-07 06:36:15.788991+00:00 duration:45.778048
[2025-04-07T06:36:15.793+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): run_minio_script> dag:<DAG: daily_weather_etl> dagrun:<DagRun daily_weather_etl @ 2025-04-04 07:00:00+00:00: scheduled__2025-04-04T07:00:00+00:00, state:running, queued_at: 2025-04-07 06:34:36.334592+00:00. externally triggered: False>
[2025-04-07T06:36:15.795+0000] {logging_mixin.py:190} INFO - Failure caused by Task received SIGTERM signal
[2025-04-07T06:36:15.797+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_weather_etl, task_id=run_minio_script, run_id=scheduled__2025-04-04T07:00:00+00:00, execution_date=20250404T070000, start_date=20250407T063530, end_date=20250407T063615
[2025-04-07T06:36:15.810+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-07T06:36:15.812+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 228 for task run_minio_script ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(daily_weather_etl, run_minio_script, scheduled__2025-04-04T07:00:00+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'run_minio_script', 'dag_id': 'daily_weather_etl', 'run_id': 'scheduled__2025-04-04T07:00:00+00:00', 'map_index': -1, 'start_date': datetime.datetime(2025, 4, 7, 6, 35, 30, 10943, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2025, 4, 7, 6, 36, 15, 788991, tzinfo=Timezone('UTC')), 'duration': 45}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 389)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 257, in execute
    result = self._run_inline_command(bash_path=bash_path, env=env)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 284, in _run_inline_command
    return self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/hooks/subprocess.py", line 104, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3097, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.ForeignKeyViolation: insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(daily_weather_etl, run_minio_script, scheduled__2025-04-04T07:00:00+00:00, -1) is not present in table "task_instance".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 328, in _run_raw_task
    ti.handle_failure(e, test_mode, context, session=session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3434, in handle_failure
    _handle_failure(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1244, in _handle_failure
    TaskInstance.save_to_db(task_instance, session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3402, in save_to_db
    ti.get_dagrun().refresh_from_db()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 57, in create_session
    session.commit()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1454, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 832, in commit
    self._prepare_impl()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 811, in _prepare_impl
    self.session.flush()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3449, in flush
    self._flush(objects)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3589, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3549, in _flush
    flush_context.execute()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(daily_weather_etl, run_minio_script, scheduled__2025-04-04T07:00:00+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'run_minio_script', 'dag_id': 'daily_weather_etl', 'run_id': 'scheduled__2025-04-04T07:00:00+00:00', 'map_index': -1, 'start_date': datetime.datetime(2025, 4, 7, 6, 35, 30, 10943, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2025, 4, 7, 6, 36, 15, 788991, tzinfo=Timezone('UTC')), 'duration': 45}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2025-04-07T06:36:15.858+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=780, status='terminated', started='06:35:53') (780) terminated with exit code None
[2025-04-07T06:36:15.924+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=689, status='terminated', started='06:35:51') (689) terminated with exit code None
[2025-04-07T06:36:15.926+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=724, status='terminated', started='06:35:51') (724) terminated with exit code None
[2025-04-07T06:36:15.928+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=802, status='terminated', started='06:35:53') (802) terminated with exit code None
[2025-04-07T06:36:15.931+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=773, status='terminated', started='06:35:53') (773) terminated with exit code None
[2025-04-07T06:36:15.933+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=784, status='terminated', started='06:35:53') (784) terminated with exit code None
[2025-04-07T06:36:15.936+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=797, status='terminated', started='06:35:53') (797) terminated with exit code None
[2025-04-07T06:36:15.991+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=394, status='terminated', started='06:35:30') (394) terminated with exit code None
[2025-04-07T06:36:15.995+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=674, status='terminated', started='06:35:51') (674) terminated with exit code None
[2025-04-07T06:36:15.998+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=776, status='terminated', started='06:35:53') (776) terminated with exit code None
[2025-04-07T06:36:16.001+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=788, status='terminated', started='06:35:53') (788) terminated with exit code None
[2025-04-07T06:36:16.006+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=813, status='terminated', started='06:35:53') (813) terminated with exit code None
[2025-04-07T06:36:16.013+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=698, status='terminated', started='06:35:51') (698) terminated with exit code None
[2025-04-07T06:36:16.015+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=716, status='terminated', started='06:35:51') (716) terminated with exit code None
[2025-04-07T06:36:16.018+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=673, status='terminated', started='06:35:51') (673) terminated with exit code None
[2025-04-07T06:36:16.020+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=389, status='terminated', exitcode=1, started='06:35:30') (389) terminated with exit code 1
[2025-04-07T06:36:16.023+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=684, status='terminated', started='06:35:51') (684) terminated with exit code None
[2025-04-07T06:36:16.026+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=708, status='terminated', started='06:35:51') (708) terminated with exit code None
[2025-04-07T06:36:16.029+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=670, status='terminated', started='06:35:49') (670) terminated with exit code None
[2025-04-07T06:36:16.031+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=745, status='terminated', started='06:35:51') (745) terminated with exit code None
[2025-04-07T06:36:16.539+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=409, status='terminated', started='06:35:32') (409) terminated with exit code None
[2025-04-07T07:00:09.782+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-07T07:00:09.912+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_weather_etl.run_minio_script scheduled__2025-04-04T07:00:00+00:00 [queued]>
[2025-04-07T07:00:09.924+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_weather_etl.run_minio_script scheduled__2025-04-04T07:00:00+00:00 [queued]>
[2025-04-07T07:00:09.925+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-07T07:00:09.939+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_minio_script> on 2025-04-04 07:00:00+00:00
[2025-04-07T07:00:09.946+0000] {standard_task_runner.py:72} INFO - Started process 3468 to run task
[2025-04-07T07:00:09.949+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'daily_weather_etl', 'run_minio_script', 'scheduled__2025-04-04T07:00:00+00:00', '--job-id', '230', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpyawtwwje']
[2025-04-07T07:00:09.951+0000] {standard_task_runner.py:105} INFO - Job 230: Subtask run_minio_script
[2025-04-07T07:00:09.998+0000] {task_command.py:467} INFO - Running <TaskInstance: daily_weather_etl.run_minio_script scheduled__2025-04-04T07:00:00+00:00 [running]> on host 3c3c1f66214b
[2025-04-07T07:00:10.072+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_weather_etl' AIRFLOW_CTX_TASK_ID='run_minio_script' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T07:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-04T07:00:00+00:00'
[2025-04-07T07:00:10.075+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-07T07:00:10.076+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-07T07:00:10.077+0000] {logging_mixin.py:190} INFO - Current task name:run_minio_script state:running start_date:2025-04-07 07:00:09.913729+00:00
[2025-04-07T07:00:10.078+0000] {logging_mixin.py:190} INFO - Dag name:daily_weather_etl and current dag run status:running
[2025-04-07T07:00:10.079+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-07T07:00:10.080+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-07T07:00:10.081+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/minio.py']
[2025-04-07T07:00:10.091+0000] {subprocess.py:99} INFO - Output:
[2025-04-07T07:00:12.613+0000] {subprocess.py:106} INFO - Setting default log level to "WARN".
[2025-04-07T07:00:12.614+0000] {subprocess.py:106} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-04-07T07:00:12.820+0000] {subprocess.py:106} INFO - 25/04/07 07:00:12 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-04-07T07:00:25.142+0000] {subprocess.py:106} INFO - [Stage 0:>                                                          (0 + 8) / 8]                                                                                +-----+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-04-07T07:00:25.143+0000] {subprocess.py:106} INFO - |city |date      |time |temperature|wind_kph|humidity|feelslike|precip_mm|text         |icon                                          |
[2025-04-07T07:00:25.144+0000] {subprocess.py:106} INFO - +-----+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-04-07T07:00:25.146+0000] {subprocess.py:106} INFO - |elche|2025-04-05|22:00|17.6       |5.1     |59      |17.6     |0.0      |Cloudy       |//cdn.weatherapi.com/weather/64x64/day/119.png|
[2025-04-07T07:00:25.147+0000] {subprocess.py:106} INFO - |elche|2025-04-05|15:00|24.5       |16.0    |22      |24.5     |0.0      |Partly Cloudy|//cdn.weatherapi.com/weather/64x64/day/116.png|
[2025-04-07T07:00:25.148+0000] {subprocess.py:106} INFO - |elche|2025-04-05|09:00|15.4       |11.7    |61      |15.4     |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-04-07T07:00:25.149+0000] {subprocess.py:106} INFO - |elche|2025-04-05|04:00|16.1       |15.7    |58      |16.1     |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-04-07T07:00:25.154+0000] {subprocess.py:106} INFO - +-----+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-04-07T07:00:25.156+0000] {subprocess.py:106} INFO - 
[2025-04-07T07:00:25.158+0000] {subprocess.py:106} INFO - +------+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-04-07T07:00:25.159+0000] {subprocess.py:106} INFO - |city  |date      |time |temperature|wind_kph|humidity|feelslike|precip_mm|text         |icon                                          |
[2025-04-07T07:00:25.162+0000] {subprocess.py:106} INFO - +------+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-04-07T07:00:25.163+0000] {subprocess.py:106} INFO - |madrid|2025-04-05|04:00|9.2        |12.5    |93      |9.2      |0.0      |Cloudy       |//cdn.weatherapi.com/weather/64x64/day/119.png|
[2025-04-07T07:00:25.165+0000] {subprocess.py:106} INFO - |madrid|2025-04-05|09:00|8.8        |9.7     |91      |8.8      |0.0      |Partly Cloudy|//cdn.weatherapi.com/weather/64x64/day/116.png|
[2025-04-07T07:00:25.167+0000] {subprocess.py:106} INFO - |madrid|2025-04-05|22:00|11.2       |6.6     |74      |11.2     |0.0      |Cloudy       |//cdn.weatherapi.com/weather/64x64/day/119.png|
[2025-04-07T07:00:25.168+0000] {subprocess.py:106} INFO - |madrid|2025-04-05|15:00|14.3       |7.8     |58      |14.3     |0.1      |Light Drizzle|//cdn.weatherapi.com/weather/64x64/day/176.png|
[2025-04-07T07:00:25.169+0000] {subprocess.py:106} INFO - +------+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-04-07T07:00:25.170+0000] {subprocess.py:106} INFO - 
[2025-04-07T07:00:25.172+0000] {subprocess.py:106} INFO - +--------------------+----------+-----+-----------+--------+--------+---------+---------+------------+----------------------------------------------+
[2025-04-07T07:00:25.173+0000] {subprocess.py:106} INFO - |city                |date      |time |temperature|wind_kph|humidity|feelslike|precip_mm|text        |icon                                          |
[2025-04-07T07:00:25.175+0000] {subprocess.py:106} INFO - +--------------------+----------+-----+-----------+--------+--------+---------+---------+------------+----------------------------------------------+
[2025-04-07T07:00:25.176+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-05|22:00|16.5       |3.4     |68      |16.5     |0.0      |Mostly Clear|//cdn.weatherapi.com/weather/64x64/day/116.png|
[2025-04-07T07:00:25.178+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-05|04:00|13.6       |4.9     |81      |13.6     |0.0      |Sunny       |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-04-07T07:00:25.180+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-05|15:00|23.9       |16.5    |24      |23.9     |0.0      |Sunny       |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-04-07T07:00:25.181+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-05|09:00|15.6       |7.9     |60      |15.6     |0.0      |Sunny       |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-04-07T07:00:25.182+0000] {subprocess.py:106} INFO - +--------------------+----------+-----+-----------+--------+--------+---------+---------+------------+----------------------------------------------+
[2025-04-07T07:00:25.183+0000] {subprocess.py:106} INFO - 
[2025-04-07T07:00:25.185+0000] {subprocess.py:106} INFO - +----------+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-04-07T07:00:25.187+0000] {subprocess.py:106} INFO - |city      |date      |time |temperature|wind_kph|humidity|feelslike|precip_mm|text         |icon                                          |
[2025-04-07T07:00:25.189+0000] {subprocess.py:106} INFO - +----------+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-04-07T07:00:25.190+0000] {subprocess.py:106} INFO - |torrevieja|2025-04-05|04:00|14.0       |4.9     |98      |14.0     |0.0      |Partly Cloudy|//cdn.weatherapi.com/weather/64x64/day/116.png|
[2025-04-07T07:00:25.191+0000] {subprocess.py:106} INFO - |torrevieja|2025-04-05|09:00|15.3       |12.1    |72      |15.3     |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-04-07T07:00:25.192+0000] {subprocess.py:106} INFO - |torrevieja|2025-04-05|22:00|15.7       |5.8     |72      |15.7     |0.0      |Cloudy       |//cdn.weatherapi.com/weather/64x64/day/119.png|
[2025-04-07T07:00:25.194+0000] {subprocess.py:106} INFO - |torrevieja|2025-04-05|15:00|22.8       |12.2    |36      |22.8     |0.0      |Cloudy       |//cdn.weatherapi.com/weather/64x64/day/119.png|
[2025-04-07T07:00:25.197+0000] {subprocess.py:106} INFO - +----------+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-04-07T07:00:25.199+0000] {subprocess.py:106} INFO - 
[2025-04-07T07:00:25.200+0000] {subprocess.py:106} INFO - +--------+----------+-----+-----------+--------+--------+---------+---------+------------+----------------------------------------------+
[2025-04-07T07:00:25.201+0000] {subprocess.py:106} INFO - |city    |date      |time |temperature|wind_kph|humidity|feelslike|precip_mm|text        |icon                                          |
[2025-04-07T07:00:25.203+0000] {subprocess.py:106} INFO - +--------+----------+-----+-----------+--------+--------+---------+---------+------------+----------------------------------------------+
[2025-04-07T07:00:25.204+0000] {subprocess.py:106} INFO - |valencia|2025-04-05|09:00|14.4       |15.8    |66      |14.4     |0.0      |Sunny       |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-04-07T07:00:25.205+0000] {subprocess.py:106} INFO - |valencia|2025-04-05|15:00|23.3       |12.1    |27      |23.3     |0.0      |Sunny       |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-04-07T07:00:25.207+0000] {subprocess.py:106} INFO - |valencia|2025-04-05|04:00|13.3       |7.3     |87      |13.3     |0.0      |Sunny       |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-04-07T07:00:25.210+0000] {subprocess.py:106} INFO - |valencia|2025-04-05|22:00|17.2       |8.1     |58      |17.2     |0.0      |Mostly Clear|//cdn.weatherapi.com/weather/64x64/day/116.png|
[2025-04-07T07:00:25.211+0000] {subprocess.py:106} INFO - +--------+----------+-----+-----------+--------+--------+---------+---------+------------+----------------------------------------------+
[2025-04-07T07:00:25.214+0000] {subprocess.py:106} INFO - 
[2025-04-07T07:00:30.343+0000] {subprocess.py:106} INFO - +--------------------+----------+-----+-----------+--------+--------+---------+---------+-------------+--------------------+
[2025-04-07T07:00:30.344+0000] {subprocess.py:106} INFO - |                city|      date| time|temperature|wind_kph|humidity|feelslike|precip_mm|         text|                icon|
[2025-04-07T07:00:30.345+0000] {subprocess.py:106} INFO - +--------------------+----------+-----+-----------+--------+--------+---------+---------+-------------+--------------------+
[2025-04-07T07:00:30.346+0000] {subprocess.py:106} INFO - |               elche|2025-04-05|04:00|       16.1|    15.7|      58|     16.1|      0.0|        Sunny|//cdn.weatherapi....|
[2025-04-07T07:00:30.348+0000] {subprocess.py:106} INFO - |               elche|2025-04-05|09:00|       15.4|    11.7|      61|     15.4|      0.0|        Sunny|//cdn.weatherapi....|
[2025-04-07T07:00:30.349+0000] {subprocess.py:106} INFO - |               elche|2025-04-05|15:00|       24.5|    16.0|      22|     24.5|      0.0|Partly Cloudy|//cdn.weatherapi....|
[2025-04-07T07:00:30.350+0000] {subprocess.py:106} INFO - |               elche|2025-04-05|22:00|       17.6|     5.1|      59|     17.6|      0.0|       Cloudy|//cdn.weatherapi....|
[2025-04-07T07:00:30.351+0000] {subprocess.py:106} INFO - |              madrid|2025-04-05|04:00|        9.2|    12.5|      93|      9.2|      0.0|       Cloudy|//cdn.weatherapi....|
[2025-04-07T07:00:30.352+0000] {subprocess.py:106} INFO - |              madrid|2025-04-05|09:00|        8.8|     9.7|      91|      8.8|      0.0|Partly Cloudy|//cdn.weatherapi....|
[2025-04-07T07:00:30.352+0000] {subprocess.py:106} INFO - |              madrid|2025-04-05|15:00|       14.3|     7.8|      58|     14.3|      0.1|Light Drizzle|//cdn.weatherapi....|
[2025-04-07T07:00:30.353+0000] {subprocess.py:106} INFO - |              madrid|2025-04-05|22:00|       11.2|     6.6|      74|     11.2|      0.0|       Cloudy|//cdn.weatherapi....|
[2025-04-07T07:00:30.354+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-05|04:00|       13.6|     4.9|      81|     13.6|      0.0|        Sunny|//cdn.weatherapi....|
[2025-04-07T07:00:30.355+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-05|09:00|       15.6|     7.9|      60|     15.6|      0.0|        Sunny|//cdn.weatherapi....|
[2025-04-07T07:00:30.356+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-05|15:00|       23.9|    16.5|      24|     23.9|      0.0|        Sunny|//cdn.weatherapi....|
[2025-04-07T07:00:30.357+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-05|22:00|       16.5|     3.4|      68|     16.5|      0.0| Mostly Clear|//cdn.weatherapi....|
[2025-04-07T07:00:30.358+0000] {subprocess.py:106} INFO - |          torrevieja|2025-04-05|04:00|       14.0|     4.9|      98|     14.0|      0.0|Partly Cloudy|//cdn.weatherapi....|
[2025-04-07T07:00:30.359+0000] {subprocess.py:106} INFO - |          torrevieja|2025-04-05|09:00|       15.3|    12.1|      72|     15.3|      0.0|        Sunny|//cdn.weatherapi....|
[2025-04-07T07:00:30.360+0000] {subprocess.py:106} INFO - |          torrevieja|2025-04-05|15:00|       22.8|    12.2|      36|     22.8|      0.0|       Cloudy|//cdn.weatherapi....|
[2025-04-07T07:00:30.361+0000] {subprocess.py:106} INFO - |          torrevieja|2025-04-05|22:00|       15.7|     5.8|      72|     15.7|      0.0|       Cloudy|//cdn.weatherapi....|
[2025-04-07T07:00:30.362+0000] {subprocess.py:106} INFO - |            valencia|2025-04-05|04:00|       13.3|     7.3|      87|     13.3|      0.0|        Sunny|//cdn.weatherapi....|
[2025-04-07T07:00:30.363+0000] {subprocess.py:106} INFO - |            valencia|2025-04-05|09:00|       14.4|    15.8|      66|     14.4|      0.0|        Sunny|//cdn.weatherapi....|
[2025-04-07T07:00:30.364+0000] {subprocess.py:106} INFO - |            valencia|2025-04-05|15:00|       23.3|    12.1|      27|     23.3|      0.0|        Sunny|//cdn.weatherapi....|
[2025-04-07T07:00:30.365+0000] {subprocess.py:106} INFO - |            valencia|2025-04-05|22:00|       17.2|     8.1|      58|     17.2|      0.0| Mostly Clear|//cdn.weatherapi....|
[2025-04-07T07:00:30.366+0000] {subprocess.py:106} INFO - +--------------------+----------+-----+-----------+--------+--------+---------+---------+-------------+--------------------+
[2025-04-07T07:00:30.367+0000] {subprocess.py:106} INFO - 
[2025-04-07T07:00:30.368+0000] {subprocess.py:106} INFO - Nombre de la carpeta: 2025-04-05
[2025-04-07T07:00:30.369+0000] {subprocess.py:106} INFO - Archivo Parquet generado: /tmp/tmpzkhsct16/2025-04-05/part-00000-a810899a-cc34-45bb-913f-5b7403279794-c000.snappy.parquet
[2025-04-07T07:00:30.370+0000] {subprocess.py:106} INFO - Archivo subido correctamente a MinIO en: 2025-04-05/2025-04-05.parquet
[2025-04-07T07:00:30.872+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-07T07:00:30.893+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-07T07:00:30.895+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=daily_weather_etl, task_id=run_minio_script, run_id=scheduled__2025-04-04T07:00:00+00:00, execution_date=20250404T070000, start_date=20250407T070009, end_date=20250407T070030
[2025-04-07T07:00:30.915+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-07T07:00:30.917+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-07T07:00:30.918+0000] {logging_mixin.py:190} INFO - Dag name:daily_weather_etl queued_at:2025-04-07 07:00:00.914090+00:00
[2025-04-07T07:00:30.919+0000] {logging_mixin.py:190} INFO - Task hostname:3c3c1f66214b operator:BashOperator
[2025-04-07T07:00:30.954+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-07T07:00:30.977+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-07T07:00:30.980+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
