[2025-03-30T10:25:58.854+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T10:25:59.027+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_weather_etl.run_main_script scheduled__2025-03-29T08:00:00+00:00 [queued]>
[2025-03-30T10:25:59.039+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_weather_etl.run_main_script scheduled__2025-03-29T08:00:00+00:00 [queued]>
[2025-03-30T10:25:59.040+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-30T10:25:59.066+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_main_script> on 2025-03-29 08:00:00+00:00
[2025-03-30T10:25:59.073+0000] {standard_task_runner.py:72} INFO - Started process 57 to run task
[2025-03-30T10:25:59.078+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'daily_weather_etl', 'run_main_script', 'scheduled__2025-03-29T08:00:00+00:00', '--job-id', '141', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpw2dlcjzc']
[2025-03-30T10:25:59.081+0000] {standard_task_runner.py:105} INFO - Job 141: Subtask run_main_script
[2025-03-30T10:25:59.148+0000] {task_command.py:467} INFO - Running <TaskInstance: daily_weather_etl.run_main_script scheduled__2025-03-29T08:00:00+00:00 [running]> on host 3c3c1f66214b
[2025-03-30T10:25:59.232+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_weather_etl' AIRFLOW_CTX_TASK_ID='run_main_script' AIRFLOW_CTX_EXECUTION_DATE='2025-03-29T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-29T08:00:00+00:00'
[2025-03-30T10:25:59.234+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-30T10:25:59.235+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-30T10:25:59.236+0000] {logging_mixin.py:190} INFO - Current task name:run_main_script state:running start_date:2025-03-30 10:25:59.028623+00:00
[2025-03-30T10:25:59.236+0000] {logging_mixin.py:190} INFO - Dag name:daily_weather_etl and current dag run status:running
[2025-03-30T10:25:59.237+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-30T10:25:59.238+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-30T10:25:59.240+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/main.py']
[2025-03-30T10:25:59.249+0000] {subprocess.py:99} INFO - Output:
[2025-03-30T10:26:00.225+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-03-30T10:26:00.226+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/main.py", line 3, in <module>
[2025-03-30T10:26:00.227+0000] {subprocess.py:106} INFO -     from utils import create_historical, check_city_minio
[2025-03-30T10:26:00.228+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/utils.py", line 8, in <module>
[2025-03-30T10:26:00.228+0000] {subprocess.py:106} INFO -     from config import API_KEY
[2025-03-30T10:26:00.229+0000] {subprocess.py:106} INFO - ImportError: cannot import name 'API_KEY' from 'config' (/opt/***/dags/config.py)
[2025-03-30T10:26:00.301+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-30T10:26:00.312+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-30T10:26:00.322+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-30T10:26:00.323+0000] {logging_mixin.py:190} INFO - Task start:2025-03-30 10:25:59.028623+00:00 end:2025-03-30 10:26:00.321930+00:00 duration:1.293307
[2025-03-30T10:26:00.324+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): run_main_script> dag:<DAG: daily_weather_etl> dagrun:<DagRun daily_weather_etl @ 2025-03-29 08:00:00+00:00: scheduled__2025-03-29T08:00:00+00:00, state:running, queued_at: 2025-03-30 10:25:52.225372+00:00. externally triggered: False>
[2025-03-30T10:26:00.325+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2025-03-30T10:26:00.325+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_weather_etl, task_id=run_main_script, run_id=scheduled__2025-03-29T08:00:00+00:00, execution_date=20250329T080000, start_date=20250330T102559, end_date=20250330T102600
[2025-03-30T10:26:00.353+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-30T10:26:00.354+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 141 for task run_main_script (Bash command failed. The command returned a non-zero exit code 1.; 57)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-30T10:26:00.415+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-30T10:26:00.436+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T10:26:00.448+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-31T06:28:21.513+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T06:28:21.544+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_weather_etl.run_main_script scheduled__2025-03-29T08:00:00+00:00 [queued]>
[2025-03-31T06:28:21.558+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_weather_etl.run_main_script scheduled__2025-03-29T08:00:00+00:00 [queued]>
[2025-03-31T06:28:21.560+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-31T06:28:21.595+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_main_script> on 2025-03-29 08:00:00+00:00
[2025-03-31T06:28:21.614+0000] {standard_task_runner.py:72} INFO - Started process 119 to run task
[2025-03-31T06:28:21.619+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'daily_weather_etl', 'run_main_script', 'scheduled__2025-03-29T08:00:00+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp7xqm4zx5']
[2025-03-31T06:28:21.630+0000] {standard_task_runner.py:105} INFO - Job 166: Subtask run_main_script
[2025-03-31T06:28:21.731+0000] {task_command.py:467} INFO - Running <TaskInstance: daily_weather_etl.run_main_script scheduled__2025-03-29T08:00:00+00:00 [running]> on host 3c3c1f66214b
[2025-03-31T06:28:22.136+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_weather_etl' AIRFLOW_CTX_TASK_ID='run_main_script' AIRFLOW_CTX_EXECUTION_DATE='2025-03-29T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-29T08:00:00+00:00'
[2025-03-31T06:28:22.138+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-31T06:28:22.141+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-31T06:28:22.143+0000] {logging_mixin.py:190} INFO - Current task name:run_main_script state:running start_date:2025-03-31 06:28:21.545564+00:00
[2025-03-31T06:28:22.144+0000] {logging_mixin.py:190} INFO - Dag name:daily_weather_etl and current dag run status:running
[2025-03-31T06:28:22.146+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-31T06:28:22.148+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-31T06:28:22.150+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/main.py']
[2025-03-31T06:28:22.168+0000] {subprocess.py:99} INFO - Output:
[2025-03-31T06:28:25.617+0000] {subprocess.py:106} INFO - 25/03/31 06:28:25 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-31T06:28:25.869+0000] {subprocess.py:106} INFO - Setting default log level to "WARN".
[2025-03-31T06:28:25.870+0000] {subprocess.py:106} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-03-31T06:28:27.079+0000] {subprocess.py:106} INFO - 25/03/31 06:28:27 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2025-03-31T06:29:11.228+0000] {subprocess.py:106} INFO - [Stage 0:>                                                          (0 + 8) / 8][Stage 0:===================================================>       (7 + 1) / 8]                                                                                [Stage 5:>                                                          (0 + 1) / 1]                                                                                Ciudades registradas:
[2025-03-31T06:29:11.232+0000] {subprocess.py:106} INFO - Vamos a crear un histórico de san juan de alicante
[2025-03-31T06:29:11.233+0000] {subprocess.py:106} INFO - +--------------------+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-03-31T06:29:11.234+0000] {subprocess.py:106} INFO - |city                |date      |time |temperature|wind_kph|humidity|feelslike|precip_mm|text         |icon                                          |
[2025-03-31T06:29:11.236+0000] {subprocess.py:106} INFO - +--------------------+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-03-31T06:29:11.237+0000] {subprocess.py:106} INFO - |san juan de alicante|2021-01-01|04:00|6.7        |9.8     |68      |6.7      |0.0      |Partly Cloudy|//cdn.weatherapi.com/weather/64x64/day/116.png|
[2025-03-31T06:29:11.238+0000] {subprocess.py:106} INFO - |san juan de alicante|2021-01-01|09:00|7.4        |13.3    |71      |7.4      |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-31T06:29:11.239+0000] {subprocess.py:106} INFO - |san juan de alicante|2021-01-01|15:00|13.7       |21.4    |34      |13.7     |0.0      |Mostly Clear |//cdn.weatherapi.com/weather/64x64/day/116.png|
[2025-03-31T06:29:11.240+0000] {subprocess.py:106} INFO - |san juan de alicante|2021-01-01|22:00|9.0        |22.1    |46      |9.0      |0.0      |Mostly Clear |//cdn.weatherapi.com/weather/64x64/day/116.png|
[2025-03-31T06:29:11.241+0000] {subprocess.py:106} INFO - |san juan de alicante|2021-01-02|04:00|6.4        |15.0    |59      |6.4      |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-31T06:29:11.242+0000] {subprocess.py:106} INFO - |san juan de alicante|2021-01-02|09:00|5.5        |26.3    |49      |5.5      |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-31T06:29:11.243+0000] {subprocess.py:106} INFO - |san juan de alicante|2021-01-02|15:00|10.7       |32.0    |33      |10.7     |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-31T06:29:11.244+0000] {subprocess.py:106} INFO - |san juan de alicante|2021-01-02|22:00|5.8        |9.2     |46      |5.8      |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-31T06:29:11.246+0000] {subprocess.py:106} INFO - |san juan de alicante|2021-01-03|04:00|5.7        |25.1    |45      |5.7      |0.0      |Cloudy       |//cdn.weatherapi.com/weather/64x64/day/119.png|
[2025-03-31T06:29:11.247+0000] {subprocess.py:106} INFO - |san juan de alicante|2021-01-03|09:00|4.6        |21.3    |45      |4.6      |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-31T06:29:11.248+0000] {subprocess.py:106} INFO - |san juan de alicante|2021-01-03|15:00|12.5       |28.7    |28      |12.5     |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-31T06:29:11.249+0000] {subprocess.py:106} INFO - |san juan de alicante|2021-01-03|22:00|7.4        |11.2    |42      |7.4      |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-31T06:29:11.250+0000] {subprocess.py:106} INFO - |san juan de alicante|2021-01-04|04:00|4.2        |9.1     |56      |4.2      |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-31T06:29:11.251+0000] {subprocess.py:106} INFO - |san juan de alicante|2021-01-04|09:00|4.6        |11.5    |63      |4.6      |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-31T06:29:11.252+0000] {subprocess.py:106} INFO - |san juan de alicante|2021-01-04|15:00|12.4       |24.0    |36      |12.4     |0.0      |Mostly Clear |//cdn.weatherapi.com/weather/64x64/day/116.png|
[2025-03-31T06:29:11.253+0000] {subprocess.py:106} INFO - |san juan de alicante|2021-01-04|22:00|8.5        |18.9    |56      |8.5      |0.0      |Mostly Clear |//cdn.weatherapi.com/weather/64x64/day/116.png|
[2025-03-31T06:29:11.254+0000] {subprocess.py:106} INFO - |san juan de alicante|2021-01-05|04:00|5.1        |9.4     |65      |5.1      |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-31T06:29:11.255+0000] {subprocess.py:106} INFO - |san juan de alicante|2021-01-05|09:00|2.5        |9.8     |65      |2.5      |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-31T06:29:11.256+0000] {subprocess.py:106} INFO - |san juan de alicante|2021-01-05|15:00|12.2       |8.3     |24      |12.2     |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-31T06:29:11.257+0000] {subprocess.py:106} INFO - |san juan de alicante|2021-01-05|22:00|7.5        |6.6     |48      |7.5      |0.0      |Cloudy       |//cdn.weatherapi.com/weather/64x64/day/119.png|
[2025-03-31T06:29:11.258+0000] {subprocess.py:106} INFO - +--------------------+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-03-31T06:29:11.260+0000] {subprocess.py:106} INFO - only showing top 20 rows
[2025-03-31T06:29:11.261+0000] {subprocess.py:106} INFO - 
[2025-03-31T06:29:11.262+0000] {subprocess.py:106} INFO - Nombre de la carpeta: san_juan_de_alicante__38_4__0_43
[2025-03-31T06:29:11.263+0000] {subprocess.py:106} INFO - Archivo Parquet generado: /tmp/tmp0k8z4prh/san_juan_de_alicante__38_4__0_43/part-00000-86b5c360-96d8-4a36-84f8-c15bf4d86419-c000.snappy.parquet
[2025-03-31T06:29:11.264+0000] {subprocess.py:106} INFO - Archivo subido correctamente a MinIO en: san_juan_de_alicante__38_4__0_43/san_juan_de_alicante__38_4__0_43.parquet
[2025-03-31T06:29:11.265+0000] {subprocess.py:106} INFO - Datos registrados correctamente en la bbdd
[2025-03-31T06:29:11.769+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-31T06:29:11.789+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-31T06:29:11.790+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=daily_weather_etl, task_id=run_main_script, run_id=scheduled__2025-03-29T08:00:00+00:00, execution_date=20250329T080000, start_date=20250331T062821, end_date=20250331T062911
[2025-03-31T06:29:11.809+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-31T06:29:11.811+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-31T06:29:11.811+0000] {logging_mixin.py:190} INFO - Dag name:daily_weather_etl queued_at:2025-03-31 06:28:18.571526+00:00
[2025-03-31T06:29:11.812+0000] {logging_mixin.py:190} INFO - Task hostname:3c3c1f66214b operator:BashOperator
[2025-03-31T06:29:11.832+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-31T06:29:11.850+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-31T06:29:11.853+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-31T07:13:49.485+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T07:13:49.514+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_weather_etl.run_main_script scheduled__2025-03-29T08:00:00+00:00 [queued]>
[2025-03-31T07:13:49.529+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_weather_etl.run_main_script scheduled__2025-03-29T08:00:00+00:00 [queued]>
[2025-03-31T07:13:49.530+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-31T07:13:49.549+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_main_script> on 2025-03-29 08:00:00+00:00
[2025-03-31T07:13:49.557+0000] {standard_task_runner.py:72} INFO - Started process 8895 to run task
[2025-03-31T07:13:49.563+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'daily_weather_etl', 'run_main_script', 'scheduled__2025-03-29T08:00:00+00:00', '--job-id', '196', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp04yl8yjc']
[2025-03-31T07:13:49.566+0000] {standard_task_runner.py:105} INFO - Job 196: Subtask run_main_script
[2025-03-31T07:13:49.636+0000] {task_command.py:467} INFO - Running <TaskInstance: daily_weather_etl.run_main_script scheduled__2025-03-29T08:00:00+00:00 [running]> on host 3c3c1f66214b
[2025-03-31T07:13:50.009+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_weather_etl' AIRFLOW_CTX_TASK_ID='run_main_script' AIRFLOW_CTX_EXECUTION_DATE='2025-03-29T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-29T08:00:00+00:00'
[2025-03-31T07:13:50.011+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-31T07:13:50.012+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-31T07:13:50.013+0000] {logging_mixin.py:190} INFO - Current task name:run_main_script state:running start_date:2025-03-31 07:13:49.516640+00:00
[2025-03-31T07:13:50.015+0000] {logging_mixin.py:190} INFO - Dag name:daily_weather_etl and current dag run status:running
[2025-03-31T07:13:50.016+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-31T07:13:50.018+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-31T07:13:50.021+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/main.py']
[2025-03-31T07:13:50.036+0000] {subprocess.py:99} INFO - Output:
[2025-03-31T07:13:54.008+0000] {subprocess.py:106} INFO - 25/03/31 07:13:54 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-31T07:13:54.284+0000] {subprocess.py:106} INFO - Setting default log level to "WARN".
[2025-03-31T07:13:54.285+0000] {subprocess.py:106} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-03-31T07:13:56.368+0000] {subprocess.py:106} INFO - Ciudades registradas:
[2025-03-31T07:13:56.874+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-31T07:13:56.917+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-31T07:13:56.918+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=daily_weather_etl, task_id=run_main_script, run_id=scheduled__2025-03-29T08:00:00+00:00, execution_date=20250329T080000, start_date=20250331T071349, end_date=20250331T071356
[2025-03-31T07:13:56.960+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-31T07:13:56.962+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-31T07:13:56.963+0000] {logging_mixin.py:190} INFO - Dag name:daily_weather_etl queued_at:2025-03-31 07:13:46.991613+00:00
[2025-03-31T07:13:56.965+0000] {logging_mixin.py:190} INFO - Task hostname:3c3c1f66214b operator:BashOperator
[2025-03-31T07:13:56.983+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-31T07:13:57.027+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-31T07:13:57.031+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
